const express = require('express');
const fs = require('node:fs');
const path = require('node:path');

// Keep the public About page discoverable from every HTML page generated by
// the dashboard without duplicating navigation markup across individual routes.
const originalSend = express.response.send;

express.response.send = function kryndexaNavigationSend(body) {
  if (typeof body === 'string' && body.includes('<!doctype html>')) {
    let html = body;

    if (!html.includes('href="/about">About</a>')) {
      html = html.replace(
        /(<a href="\/">Home<\/a>\s*)(<a href="\/features">Features<\/a>)/,
        '$1<a href="/about">About</a>\n    $2',
      );
    }

    if (!html.includes('class="footer-nav"><a href="/about">About</a>')) {
      html = html.replace(
        '<nav class="footer-nav"><a href="/features">Features</a>',
        '<nav class="footer-nav"><a href="/about">About</a><span aria-hidden="true">•</span><a href="/features">Features</a>',
      );
    }

    body = html;
  }

  return originalSend.call(this, body);
};

function enhanceAboutPage(html) {
  let page = html;

  // Make the bot favicon an explicit branded image in the sticky header.
  page = page.replace(
    '<a class="about-brand" href="/"><img src="/favicon.ico" alt=""><span>Kryndexa Bot</span></a>',
    '<a class="about-brand" href="/" aria-label="Kryndexa Bot home"><img src="/favicon.ico" alt="Kryndexa Bot logo" width="38" height="38"><span>Kryndexa Bot</span></a>',
  );

  // Add a prominent bot-logo treatment to the About hero without duplicating
  // the asset or requiring a separate image file.
  if (!page.includes('class="about-hero-logo"')) {
    page = page.replace(
      '<section class="about-hero"><div><span class="about-kicker">',
      '<section class="about-hero"><div><div class="about-hero-logo"><img src="/favicon.ico" alt="Kryndexa Bot favicon"><span>Kryndexa Bot</span></div><span class="about-kicker">',
    );

    page = page.replace(
      '.about-kicker{',
      '.about-hero-logo{display:inline-flex;align-items:center;gap:12px;margin-bottom:8px;padding:8px 14px 8px 8px;border:1px solid rgba(255,255,255,.09);border-radius:18px;background:rgba(255,255,255,.035);box-shadow:0 16px 40px rgba(0,0,0,.2)}.about-hero-logo img{width:52px;height:52px;object-fit:cover;border-radius:15px;box-shadow:0 0 0 1px rgba(255,255,255,.1),0 10px 28px rgba(88,101,242,.28)}.about-hero-logo span{font-weight:850;letter-spacing:-.02em;color:#f7f8ff}.about-kicker{',
    );
  }

  return page;
}

function registerAboutRoute(app) {
  const aboutFile = path.join(__dirname, '..', '..', 'public', 'about.html');

  app.get('/about', (req, res, next) => {
    fs.readFile(aboutFile, 'utf8', (error, html) => {
      if (error) return next(error);
      res.type('html').send(enhanceAboutPage(html));
    });
  });

  // Preserve old links/bookmarks while making /about the canonical public URL.
  app.get('/about.html', (req, res) => res.redirect(301, '/about'));
}

module.exports = { registerAboutRoute };
