const express = require('express');

// Keep the public About page discoverable from every HTML page generated by
// the dashboard without duplicating navigation markup across individual routes.
// This patch runs before dashboard/server.js is loaded and only touches HTML
// strings that contain Kryndexa's standard site navigation/footer markers.
const originalSend = express.response.send;

express.response.send = function kryndexaNavigationSend(body) {
  if (typeof body === 'string' && body.includes('<!doctype html>')) {
    let html = body;

    // Signed-in and signed-out primary navigation both contain Home followed
    // by Features. Insert About between them and guard against duplicates.
    if (!html.includes('href="/about.html">About</a>')) {
      html = html.replace(
        /(<a href="\/">Home<\/a>\s*)(<a href="\/features">Features<\/a>)/,
        '$1<a href="/about.html">About</a>\n    $2',
      );
    }

    // Add About to the shared footer before Features when present.
    if (!html.includes('class="footer-nav"><a href="/about.html">About</a>')) {
      html = html.replace(
        '<nav class="footer-nav"><a href="/features">Features</a>',
        '<nav class="footer-nav"><a href="/about.html">About</a><span aria-hidden="true">•</span><a href="/features">Features</a>',
      );
    }

    body = html;
  }

  return originalSend.call(this, body);
};
