const express = require('express');

// Enable extensionless public HTML routes before dashboard/server.js creates
// its static middleware. Because public/about.html already exists, Express will
// now serve it directly at /about without exposing .html in the browser URL.
const originalStatic = express.static;
express.static = function kryndexaStatic(root, options = {}) {
  const configured = Array.isArray(options.extensions) ? options.extensions : [];
  const extensions = [...new Set([...configured, 'html'])];
  return originalStatic(root, { ...options, extensions });
};

// Keep the public About page discoverable from every HTML page generated by
// the dashboard without duplicating navigation markup across individual routes.
const originalSend = express.response.send;

express.response.send = function kryndexaNavigationSend(body) {
  if (typeof body === 'string' && body.includes('<!doctype html>')) {
    let html = body;

    if (!html.includes('href="/about">About</a>')) {
      html = html.replace(
        /(<a href="\/">Home<\/a>\s*)(<a href="\/features">Features<\/a>)/,
        '$1<a href="/about">About</a>\n    $2',
      );
    }

    if (!html.includes('class="footer-nav"><a href="/about">About</a>')) {
      html = html.replace(
        '<nav class="footer-nav"><a href="/features">Features</a>',
        '<nav class="footer-nav"><a href="/about">About</a><span aria-hidden="true">•</span><a href="/features">Features</a>',
      );
    }

    body = html;
  }

  return originalSend.call(this, body);
};

// Kept for startup compatibility. /about is served by Express static middleware
// with HTML extension resolution, which works before the HTTP server is returned.
function registerAboutRoute() {}

module.exports = { registerAboutRoute };
