'use strict';
const fs = require('node:fs');
const file = 'src/dashboard/server.js';
let s = fs.readFileSync(file, 'utf8');
const req = "const { listDiscordProducts } = require('../dashboardCommerce');\n";
if (!s.includes(req)) s = s.replace("const { getAnalytics } = require('../features/dataStore');\n", "const { getAnalytics } = require('../features/dataStore');\n" + req);
s = s.replace('    <a href="/features">Features</a>\n    <a href="/dashboard">Dashboard</a>', '    <a href="/features">Features</a>\n    <a href="/products">Products</a>\n    <a href="/dashboard">Dashboard</a>');
s = s.replace('      <a href="/features">Features</a>\n      <a href="/status">Bot &amp; Panel Status</a>', '      <a href="/features">Features</a>\n      <a href="/products">Products</a>\n      <a href="/status">Bot &amp; Panel Status</a>');
s = s.replace('<nav class="footer-nav"><a href="/features">Features</a><span aria-hidden="true">•</span><a href="/privacy">Privacy</a>', '<nav class="footer-nav"><a href="/features">Features</a><span aria-hidden="true">•</span><a href="/products">Products</a><span aria-hidden="true">•</span><a href="/privacy">Privacy</a>');
if (!s.includes("app.get('/products'")) {
  const route = `  app.get('/products', (req, res) => {\n    const products = listDiscordProducts();\n    const cards = products.map((product) => {\n      const scopeLabel = product.scope === 'guild' ? 'Server subscription' : 'User subscription';\n      const priceLabel = product.price ? \`$\${escapeHtml(product.price)} / month\` : 'Price shown by Discord';\n      const checkout = product.checkoutUrl ? \`<a class="btn" href="\${escapeHtml(product.checkoutUrl)}" target="_blank" rel="noopener noreferrer">Purchase with Discord</a>\` : '<span class="btn secondary" aria-disabled="true">SKU not configured</span>';\n      return \`<article class="product-card \${product.configured ? '' : 'product-unavailable'}"><div class="product-card-head"><div><span class="eyebrow">\${escapeHtml(scopeLabel.toUpperCase())}</span><h2>\${escapeHtml(product.name)}</h2></div><div class="product-price">\${priceLabel}</div></div><p class="product-description">\${escapeHtml(product.description)}</p><div class="product-details"><div class="product-detail"><span>Discord SKU ID</span><strong>\${product.skuId ? escapeHtml(product.skuId) : 'Not configured'}</strong></div><div class="product-detail"><span>Entitlement Scope</span><strong>\${escapeHtml(product.scope === 'guild' ? 'Discord Server' : 'Discord User')}</strong></div><div class="product-detail"><span>Kryndexa Tier</span><strong>\${escapeHtml(product.tier.toUpperCase())}</strong></div><div class="product-detail"><span>Checkout Provider</span><strong>Discord</strong></div></div><div class="product-actions">\${checkout}</div></article>\`;\n    }).join('');\n    const appId = String(process.env.DISCORD_APPLICATION_ID || process.env.DISCORD_CLIENT_ID || '').trim();\n    const storeUrl = appId ? \`https://discord.com/application-directory/\${encodeURIComponent(appId)}/store\` : '';\n    const body = \`<div class="products-page"><section class="products-hero"><div class="products-hero-copy"><span class="eyebrow">KRYNDEXA PREMIUM</span><h1>Products &amp; Discord Checkout</h1><p>Compare Kryndexa user and server subscriptions, review the configured SKU details, and complete purchases securely through Discord.</p></div>\${storeUrl ? \`<a class="btn secondary" href="\${escapeHtml(storeUrl)}" target="_blank" rel="noopener noreferrer">Open Discord Store</a>\` : ''}</section><section class="product-grid">\${cards}</section><aside class="products-note"><strong>Discord-managed checkout</strong><p>Purchases open Discord's Application Directory store. Final localized price, taxes, payment methods, renewals, receipts, refunds, and subscription management are handled by Discord.</p></aside></div>\`;\n    return res.send(page('Products • Kryndexa Bot', body, req.session.user, { path: '/products', description: 'View Kryndexa Bot Premium and Pro Discord SKU products, pricing, subscription scope and Discord checkout links.' }));\n  });\n\n`;
  s = s.replace("  app.get('/status', async (req, res) => {", route + "  app.get('/status', async (req, res) => {");
}
fs.writeFileSync(file, s);
